//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Application_to_Manage_Data_for_School_Application.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public int student_id { get; set; }
        public string student_name { get; set; }
        public Nullable<int> class_id { get; set; }
        public Nullable<int> subject_id { get; set; }
    
        public virtual Class Class { get; set; }
        public virtual Subject Subject { get; set; }
    }
}
